/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { GalaEvent, Vendor } from "./types";

export const CURATED_EVENTS: GalaEvent[] = [
  {
    id: "gala-01",
    title: "Le Palais de Cristal",
    subtitle: "The Glasshouse Gala under Moonlight",
    category: "Couture Gala",
    date: "OCTOBER 17, 2026",
    location: "Lake Como, Italy",
    venue: "Villa di Serbelloni",
    squareFootage: "18,500 SQ FT",
    guestCount: "250 ELITE",
    scentProfile: {
      top: "Bergamot & Crisp Suede",
      heart: "Damask Rose & Wet Concrete",
      base: "Oudh Royale & Somalian Lacquer",
    },
    acousticTheme: "Neo-Classical Strings & Ambient Downtempo",
    bpm: 78,
    waveformSeed: [34, 45, 62, 78, 80, 52, 41, 60, 85, 95, 75, 58, 42, 63, 82, 90, 71, 30, 48, 67, 85, 50, 40, 55, 75, 92, 80],
    blueprintUrl: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80",
    photoUrl: "https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1200&q=80",
    editorialText: "An ethereal intersection of architectural transparency and wild, uninhibited botanicals. Held within a custom-built 120-meter glass pavilion overlooking the ink-dark waters of Como, this celebratory evening bridges heavy iron frames with the delicate fragrance of over 10,000 hand-pinned white orchids.",
  },
  {
    id: "gala-02",
    title: "Nocturne Symphony",
    subtitle: "The Obsidian Ball & Alchemical Banquet",
    category: "Private Gala",
    date: "NOVEMBER 24, 2026",
    location: "Manhattan, NY",
    venue: "The Starrett-Lehigh Penthouse",
    squareFootage: "24,000 SQ FT",
    guestCount: "150 VIP",
    scentProfile: {
      top: "Crushed Black Pepper & Juniper",
      heart: "Sandalwood, Incense, & Violet",
      base: "Dry Cedarwood & Smoked Suede",
    },
    acousticTheme: "Acid Jazz Saxophone & Modern Cello Beats",
    bpm: 64,
    waveformSeed: [25, 40, 55, 70, 75, 45, 30, 40, 65, 80, 55, 40, 30, 50, 70, 85, 65, 35, 20, 45, 75, 90, 50, 30, 60, 80, 40],
    blueprintUrl: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80",
    photoUrl: "https://images.unsplash.com/photo-1469371670807-013ccf25f16a?auto=format&fit=crop&w=1200&q=80",
    editorialText: "A celebration locked entirely into the dramatic dark. Monochromatic black floral sculptures created by Parisian artisans rise from obsidian mirror tables. Every sensory vector has been designed for radical privacy, under strict dark-mode illumination where the table settings reflect solely by single-source candlelight.",
  },
  {
    id: "gala-03",
    title: "Le Solstice d'Orient",
    subtitle: "The Bamboo Forest Sanctuary Celebration",
    category: "Elite Gathering",
    date: "DECEMBER 21, 2026",
    location: "Kyoto, Japan",
    venue: "Heian Shrine Pavilion",
    squareFootage: "12,000 SQ FT",
    guestCount: "80 IMPERIAL",
    scentProfile: {
      top: "Bamboo sap & Hinoki Cypress",
      heart: "White Lotus & Smoked Tea Leaf",
      base: "Kyoto Moss & Aged Patchouli",
    },
    acousticTheme: "Traditional Shakuhachi & Granular Synthesizers",
    bpm: 52,
    waveformSeed: [15, 25, 45, 55, 60, 40, 25, 35, 50, 70, 60, 45, 30, 40, 55, 75, 60, 35, 20, 30, 50, 65, 45, 30, 40, 55, 30],
    blueprintUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80",
    photoUrl: "https://images.unsplash.com/photo-1504609773096-104ff2c73ba4?auto=format&fit=crop&w=1200&q=80",
    editorialText: "An intimate communion of extreme minimalism and cultural legacy. Within the historical quietude of the Heian Shrine gardens, guest pathways are carved from living forest textures and lit with glowing white papers. Food is prepared via ancient woodfire ash, paired with high-frequency tea compositions.",
  }
];

export const VENDOR_DIRECTORY: Vendor[] = [
  {
    id: "v-01",
    name: "Atelier de Fleurs",
    alphabet: "A",
    category: "Florals",
    location: "Paris / Milan",
    startingPrice: "$45,000",
    tiers: ["Symmetry Collection", "Imperial Flora Installation", "Signature Solstice"],
    rating: "Platinum Elite",
    about: "Horticulture Couture: Sculpting masterfully engineered botanical structures and cascading ceiling meadows suspended by invisible micro-tension cables to frame grand halls.",
    portfolioCount: 142,
    contactEmail: "atelier@fleurslux.com",
  },
  {
    id: "v-02",
    name: "Banquets d'Or",
    alphabet: "B",
    category: "Catering",
    location: "Geneva / Paris",
    startingPrice: "$75,000",
    tiers: ["Molecular Heritage Tribute", "24K Gold Ash Tasting", "Metaphysical Gastronomy"],
    rating: "3-Michelin Calibre",
    about: "Gastronomic Masterpieces: Orchestrating synesthetic course flights where micro-vapor elements and dynamic plate illumination map directly to the tempo of the soundscape.",
    portfolioCount: 96,
    contactEmail: "concierge@dorbanquets.ch",
  },
  {
    id: "v-03",
    name: "Campagne de Luxe",
    alphabet: "C",
    category: "Catering",
    location: "Reims, France",
    startingPrice: "$35,000",
    tiers: ["La Reserve Imperiale", "Prestige Blanc de Blancs", "Secret Barrel Curation"],
    rating: "Monopol Reserve",
    about: "Oenological Alchemy: Sourcing rare pre-phylloxera cellar reserves served in individually tuned lead crystal vessels engineered to resonate with the specific key of live performances.",
    portfolioCount: 64,
    contactEmail: "cellars@campagneluxe.fr",
  },
  {
    id: "v-04",
    name: "Dior Haute Couture Styling",
    alphabet: "D",
    category: "Couture",
    location: "Paris, France",
    startingPrice: "On Request",
    tiers: ["Atelier VIP Consultation", "Archival Gown Sourcing", "Global Escort Dresser"],
    rating: "Archival Exclusive",
    about: "Archival Curation: Securing historic runway pieces and hand-stitched bridal masterpieces with physical fittings hosted in secure metropolitan penthouses across five continents.",
    portfolioCount: 48,
    contactEmail: "archival-styling@diorchic.fr",
  },
  {
    id: "v-05",
    name: "Echo Soundscapes",
    alphabet: "E",
    category: "Acoustics",
    location: "London, UK",
    startingPrice: "$30,000",
    tiers: ["Spatial Sonic Blueprint", "Acoustic Attenuation Dome", "Directional Audio Rails"],
    rating: "Sonic Pioneers",
    about: "Acoustic Curation: Sculpting pristine spatial frequencies for open-air amphitheaters and vaulted stone chapels to isolate conversational whisper-zones amid symphonic peaks.",
    portfolioCount: 79,
    contactEmail: "sound@echosounds.co.uk",
  },
  {
    id: "v-06",
    name: "Feu d'Artifice Kinetic",
    alphabet: "F",
    category: "Production",
    location: "Monaco",
    startingPrice: "$60,000",
    tiers: ["Synchronized Laser Choreography", "Cold pyrotechnics Ribbon", "Ethereal Spark Cascade"],
    rating: "Royal Warrant Calibre",
    about: "Kinetic Pyrotechnics: Framing spatial structures with odorless, zero-heat digitised spark systems that release atmospheric constellations synchronized to millisecond audio beats.",
    portfolioCount: 110,
    contactEmail: "monaco@feucinemetique.mc",
  },
  {
    id: "v-07",
    name: "Grande Illuminateur",
    alphabet: "G",
    category: "Production",
    location: "Berlin / Munich",
    startingPrice: "$25,000",
    tiers: ["Chamber Candle Architect", "Kinetic Light Sculptures", "Ambient Glow Mapping"],
    rating: "Atmospheric Masters",
    about: "Luminaries of Dusk: Drafting copper-shielded candle cascades using bespoke slow-drip beeswax to map a soft, organic breathing visual temperature across historical masonry.",
    portfolioCount: 88,
    contactEmail: "contact@grandeurlicht.de",
  },
  {
    id: "v-08",
    name: "Harmonie Symphonique Noir",
    alphabet: "H",
    category: "Acoustics",
    location: "Vienna / Salzburg",
    startingPrice: "$50,000",
    tiers: ["Sextet of the Obsidian Night", "Electronic-Hybrid Orchestra", "Immersive Grand Piano Quartet"],
    rating: "Elite Classical",
    about: "Electronic Symphonies: Fusing Austrian chamber string masters with modular synthesizers to evoke massive, high-gravity soundscapes that hover between modern drone and absolute legacy.",
    portfolioCount: 115,
    contactEmail: "vienna@harmonienoir.at",
  },
  {
    id: "v-09",
    name: "Imperial Fragrance Mixology",
    alphabet: "I",
    category: "Catering",
    location: "London / New York",
    startingPrice: "$28,000",
    tiers: ["Essential Scent Bar", "The Smoked Elixir Flight", "Cryogenic botanical Mix"],
    rating: "Alchemical Curators",
    about: "Olfactory Mixology: Sculpting botanical cocktails infused with cryogenically frozen cedar bark and edible moss vapor designed to echo the room’s olfactory imprint.",
    portfolioCount: 71,
    contactEmail: "alchemist@imperialmix.co.uk",
  },
  {
    id: "v-10",
    name: "Jardin Sauvage Landscape",
    alphabet: "J",
    category: "Florals",
    location: "Tokyo / Kyoto",
    startingPrice: "$40,000",
    tiers: ["Living Bonsai Forest", "Moss Canopy Framework", "Traditional Ikebana Sculptures"],
    rating: "Zen Masters",
    about: "Botanical Brutalism: Reinterpreting raw nature with 200-year-old pine specimens, damp forest floor beddings, and riverbed stone arrangements placed in stark minimalism.",
    portfolioCount: 54,
    contactEmail: "shakuhachi@jardinsauvage.jp",
  },
  {
    id: "v-11",
    name: "Kuroko Silent Logistics",
    alphabet: "K",
    category: "Production",
    location: "Kyoto / Singapore",
    startingPrice: "$90,000",
    tiers: ["Absolute Blackbox Setup", "Synchronized Invisible Swarm", "Double-Blind Guest Routing"],
    rating: "Infinite Discretion",
    about: "Invisible Artistry: Managing rapid banquet transitions and stage conversions in total acoustic silence, utilizing false structural partitions and subterranean routing.",
    portfolioCount: 204,
    contactEmail: "discretion@kurokoshow.sg",
  },
  {
    id: "v-12",
    name: "Maison de Parfum Bespoke",
    alphabet: "M",
    category: "Scent Design",
    location: "Grasse / NY",
    startingPrice: "$55,000",
    tiers: ["Space Olfactory Signature", "Vapor Diffusion Engineering", "Gifting Atomizer Customization"],
    rating: "Master Scentists",
    about: "Spatial Olfactories: Synthesizing customized molecular signatures dispersed seamlessly through air circulation grids to enrich memories without leaving any atmospheric residue.",
    portfolioCount: 92,
    contactEmail: "grasse@maisonparfumbespoke.com",
  },
  {
    id: "v-13",
    name: "Nouvelle Gastronomie Lab",
    alphabet: "N",
    category: "Catering",
    location: "Lyon / Tokyo",
    startingPrice: "$85,000",
    tiers: ["12-Course Avant-Garde Flight", "Atmospheric Carbon Plating", "Interactive Culinary Canvas"],
    rating: "Lab Excellence",
    about: "Culinary Avant-Garde: Plating deconstructed gastronomy under liquid nitrogen vapors on custom Venetian glass frames, pairing taste textures with pure kinetic artistry.",
    portfolioCount: 130,
    contactEmail: "lab@nouvellegastronomie.com",
  },
  {
    id: "v-14",
    name: "Orphée Vinyl Archives",
    alphabet: "O",
    category: "Acoustics",
    location: "Zurich / Paris",
    startingPrice: "$22,000",
    tiers: ["Historical Press Vinyl Curation", "Ambient Sound Horizon", "Secret Analog Lounge Set"],
    rating: "Audiophile Prestige",
    about: "Audiophile Antiquities: Assembling rare mid-century analog test-pressings played exclusively through hand-assembled wooden horn columns to generate absolute spatial warmth.",
    portfolioCount: 42,
    contactEmail: "curator@orpheevinyl.ch",
  },
  {
    id: "v-15",
    name: "Pierre & Platinum Arch",
    alphabet: "P",
    category: "Production",
    location: "Brussels / Dubai",
    startingPrice: "$120,000",
    tiers: ["Brutalist Concrete Scaffolding", "Titanium Frame Ribbons", "Unpolished Marble Monoliths"],
    rating: "Architectural Lead",
    about: "Tectonic Installations: Deploying structural brutalist elements, raw marble monoliths, and custom-tensioned titanium grids to construct monumental, high-gravity stages.",
    portfolioCount: 61,
    contactEmail: "scaffold@pierreplatinum.be",
  },
  {
    id: "v-16",
    name: "Royal Archival Textiles",
    alphabet: "R",
    category: "Couture",
    location: "Florence, Italy",
    startingPrice: "$38,000",
    tiers: ["Heavy Silk Velvet Draping", "Unrefined Linen Partitions", "Metallic Thread Canopies"],
    rating: "Textile Royalty",
    about: "Imperial Drapery: Crafting massive spatial dividers, sound-dampening canopies, and velvet-walled passages using heavy silk panels hand-dyed in heritage Tuscan looms.",
    portfolioCount: 83,
    contactEmail: "textile@royaltapestry.it",
  },
  {
    id: "v-17",
    name: "Silence Custom Acoustics",
    alphabet: "S",
    category: "Acoustics",
    location: "Stockholm, Sweden",
    startingPrice: "$45,000",
    tiers: ["Sub-Bass Bone-Conduction Floor", "Frequency Cancellation Matrix", "Acoustically Invisible Room"],
    rating: "Vibrational Precision",
    about: "Sub-Sensory Acoustics: Engineering bone-conduction floor boards that propagate deep low-end frequencies directly through guests' footwear while leaving head-level zones perfectly quiet.",
    portfolioCount: 52,
    contactEmail: "engineering@silencesound.se",
  },
  {
    id: "v-18",
    name: "Torches de Marseille",
    alphabet: "T",
    category: "Production",
    location: "Marseille / Cannes",
    startingPrice: "$30,000",
    tiers: ["Ancient Hearth Fire Ring", "Smokeless Obsidian Torches", "Volcanic Dust Crucible"],
    rating: "Alchemical Fire",
    about: "Pyrogenic Atmosphere: Sculpting smokeless, scented-oil cast-iron beacon rings and volcanic dust torches certified for luxury containment in antique European estates.",
    portfolioCount: 47,
    contactEmail: "cannes@torchesmarseille.com",
  },
  {
    id: "v-19",
    name: "Vantage Suspended Stages",
    alphabet: "V",
    category: "Production",
    location: "Chicago / New York",
    startingPrice: "$110,000",
    tiers: ["Suspended High-Tension Runway", "Floating Clear Acrylic Stage", "Zero-Gravity Table Rails"],
    rating: "Structural Masters",
    about: "Gravity Defiance: Constructing high-tension translucent stages and floating dining platforms that hover weightlessly over ancient villa fountains and mirror pools.",
    portfolioCount: 73,
    contactEmail: "stages@vantagestruct.com",
  },
  {
    id: "v-20",
    name: "Whispering Pines Living Forests",
    alphabet: "W",
    category: "Florals",
    location: "Vancouver / Seattle",
    startingPrice: "$65,000",
    tiers: ["Ancient Redcedar Installation", "Living Silver Moss Wall", "Alpine Epiphytic Canopy"],
    rating: "Living Scapes",
    about: "Primeval Living Forests: Erecting massive, dew-misted alpine stands and ancient silver moss ecosystems directly inside architectural environments to provide raw sensory grounding.",
    portfolioCount: 39,
    contactEmail: "forests@whisperingpines.ca",
  },
  {
    id: "v-21",
    name: "Zenith Kinetic Holograms",
    alphabet: "Z",
    category: "Production",
    location: "Seoul / San Francisco",
    startingPrice: "$130,000",
    tiers: ["Light Beam Monolith Array", "Stark Laser Blueprint Vol", "Hyper-Frequency Air Particle Projection"],
    rating: "Digital Visionaries",
    about: "Spatial Holographs: Mapping structural blueprints, evolving flora animations, and elegant typography directly onto dense, custom-conditioned dry fog screens.",
    portfolioCount: 104,
    contactEmail: "quantum@zenithholo.co.kr",
  }
];
